%% Import data from text file.
% Script for importing data from the following text file:
%
%    ./traces/AngryBird/result.po_p2_WriteSync
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2014/08/16 04:23:50


%% Initialize variables.
function [Time Action Type BlkNo BlkCnt ProcId Proc BlkType FileName]= ParseData(filename)
% filename = './traces/AngryBird/result.po_p2_WriteSync';
delimiter = '\t';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: text (%s)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: text (%s)
%	column8: text (%s)
%   column9: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%s%s%f%f%f%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Time = dataArray{:, 1};
Action = dataArray{:, 2};
Type = dataArray{:, 3};
BlkNo = dataArray{:, 4};
BlkCnt = dataArray{:, 5};
ProcId = dataArray{:, 6};
Proc = dataArray{:, 7};
BlkType = dataArray{:, 8};
FileName = dataArray{:, 9};

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;
